service: serverless-hello-world

custom:
    settings:
        ITEMS_DYNAMODB_TABLE: serverless-hello-world-items-table2

provider:
    name: aws
    runtime: nodejs12.x
    profile: cashback
    region: us-east-1
    environment: ${self:custom.settings}

    
    #iamRoleStatements:
    #    - Effect: "Allow"
    #      Action:
    #        - "dynamodb:GetItem"
    #        - "dynamodb:PutItem"
    #      Resource:
    #        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.ITEMS_DYNAMODB_TABLE}"

    iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'
  
functions:
    hello:
        handler: handler.hello
        events:
            - http:
                path: hello
                method: get
    
    wasGreeted:
        handler: handler.wasGreeted
        events:
            - http:
                path: wasGreeted
                method: get
    
resources:
    Resources:
        ImagesTable:
            Type: "AWS::DynamoDB::Table"
            Properties:
                AttributeDefinitions:
                    - AttributeName: "firstName"
                      AttributeType: "S"
                KeySchema:
                    - AttributeName: "firstName"
                      KeyType: "HASH"
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:custom.settings.ITEMS_DYNAMODB_TABLE}